version: "3.0"
services:
  nginx:
    container_name: marketbot-frontend
    # image: 
    restart: always
    ports:
      - "8013:80"
    volumes:
      - ./nginx/log:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80"]
      interval: 1m30s
      timeout: 10s
      retries: 3
networks:
  default:
    driver: bridge