version: "3.0"
services:
  nginx:
    container_name: marketbot-frontend
    build:
      context: .
    restart: always
    environment:
      APP_BACKEND_URL: https://proxy.bananaz.tech/api/configs/
      APP_BACKEND_API_KEY: 2JCt2CjGA57T6GHhxDHJstqJx2ENvZhvvZ3trsTCSwK5HSCZ8N
    ports:
      - "8013:80"
    volumes:
      - ./nginx/log:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80"]
      interval: 1m30s
      timeout: 10s
      retries: 3